### ISSUE TITLE
errors saying 'no mirror available' and 'error refreshing available games' after update 0.2.4

### ISSUE THREAD

**Issue by victoria909909** [skrimix/QLoaderFiles#12]
I've just updated to loader 0.2.4 beta after prompted when i opened it. Now i keep getting errors saying 'no mirror available' and 'error refreshing available games'

**Comment by skrimix** [comment]
After being overloaded our servers and mirrors are down for maintenance

**Comment by victoria909909** [comment]
Thanks!
