### ISSUE TITLE
Font Loader issue

### ISSUE THREAD

**Issue by FiReLScar** [skrimix/QLoaderFiles#7]
Arch Linux [DWM]
https://pastebin.com/VmWUrRdb

I run ./Loader and it returns this, I'm thinking I might just be missing the font it needs but I'm not sure

**Comment by skrimix** [comment]
Troubleshooting section in [instructions post](https://telegra.ph/LOADER-FOR-MAC-OSXLINUX-04-16) has info about this error

> If you get a crash with message Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty. you need to install Microsoft fonts. On Arch distros simplest way is to install ttf-ms-fonts from AUR and run fc-cache --force.
